fcm:
  credentials:
    path: ENC(Gtoz0iqvq1pXcoeveeL2YJYZ+CISRlYDiYO6FIsR0I5DMcQvaNFLOd0ZW5wyOIpx4j4plznFYEwxZ7HGNViT3Q==)
app:
  domain:
    prod: ENC(5P9Iq3ZTswvqef+LtMIwKsnvQ0guIfVYyIMmNmYcjDA=)
    test: ENC(uA65wJJ2xUxoDiTPw+99JfevldmMMFdHcK2oJelBhOG1/h0A+HsR96VdRpeaRzl/)
  aws:
    s3:
      bucket: ENC(JWOQ3iliS4xmdGerB0r3eRXASu4jCbMO5cts0xF26sY=)
      region: ap-northeast-2
      public-base-url: ENC(r3T3si7pQMZjK95dKM3tir9enacrZgYGjvlGmGeZKzTmPNs4wtBOGMUbs2u531mHhKtLTup1BGrzbKh8u8+Mlk/1EFne4MVv)
    credentials:
      access-key: ENC(CIHPfitmBcHyzBwHYfDxSP3Jre5HOBqXuEm8jiMbtQU=)
      secret-key: ENC(eZi6TvjbIjfgTwccPy1WIoLNjsjD6Ed0QC4dGeRyRhBT1fjsS2ZtvwqPczmDSuYKDSkcGHi7XOU=)
server:
  port: 443
  ssl:
    enabled: true
    key-store: /app/config/keystore.p12
    key-store-password: ENC(vvUgNR9gTKm6jTSuHQDLC9QzqN3wH+vU)
    key-store-type: PKCS12

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

spring:
  jackson:
    time-zone: Asia/Seoul
  application:
    name: stockProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(o/t/6E2gqepkhCGzNBKxqTHqdl2am/LXx7oza/aQ+1ORZS9y1NoMWeYad76lBg7AnSmV5bOElouEv3o2S4NSkn6pyrZ0QGOwuskx3CIAQkPCrqYo666ODs7bHzJCu0le4Up7BlE3QRTFBBcKdlnt7KfO0V97XyIxsclC6IXj0cqkzXWLw+2vWACrmhCfdZ6RzTHqYrxRr7I=)
    username: ENC(0YcumuiWmFs1CZfK0RcslQ==)
    password: ENC(41UmOQt2/KKY36ydEZ2QpigL3PJ6oiFq)
    time-zone: Asia/Seoul
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
    show-sql: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
      enabled: false
  jwt:
    secret: ENC(ZtLQKC+5jIxK8fYB7W6XZ3mkCr3ueVGBVYTa1SfpAsnsSKUw2k5lHD+egat0VF0fyQH9apHpl5o=)
    access-expiration-ms: ENC(LC2BPxRUYKGUHFikipEopQ==)
    refresh-expiration-ms: ENC(vIwhX3e0QNiMf9DT3qx6tviWchTH1OL7)
  security:
    appkey: ENC(x03pW1tjWZPkly9PCQWLKQd94SpUnXcUGJ2y7NcdcAM5/knSG6/mnt1eEiHqIgIx)
    appsecret: ENC(lY5EPC0PWewfMk5owO0kTYSWAL5HSIW5pHXjWNl3fZggYrDWTjOHEy2zfkaO7lfIMg6OCzYkvKS9abf1ERQtcatpX/4dc1LEsCmgImvmIghj6m5r7SlBcBsSraMr70vs39wFo/9AVwiyHY0idIbrfNJwW9ZWSJM2NKDhuSo0K3hI1kDWjcVkRTRkdtjlMk4YxMqGgJ5lcx3EVmHqp7+RSYTx+j64lLUrSjt56wXQqgBI95wwzAmTq6UVJRhPyNwJ)
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ENC(a6qYAmZXBw98jgyy8ayVU15UyX7dkAXch+hs2kFJ974=)
            client-secret: ENC(qD5UR0Pj6M1+0mfxKzw0REgtfDu9kSa5)
          kakao:
            client-name: kakao
            client-id: ENC(Vb2caeNgKesY/VtHQCd1MaQ/T2nkLeBXZIW+GpL5u0Be/hExJl6OArs+pwqTFk1w)
            client-secret: ENC(WKFi2yrFkQJLWbYStPT25DgaA8RhFztzlQZnua4S9+COjqiudbwg/kySV2WHBA7u)
          google:
            client-name: google
            client-id: ENC(WFb1HLBH6ZJZdarB9dBSrdY2s7pi9ngOH1tbeBeAMYDd9NQb3vXPfBqL/Bjlu6qWD7NM9RpRiXy/w0Skhq4QU7zRw3wqxUi76OoOuAO+I2JwWpzAHOhN5g==)
            client-secret: ENC(E1oLkj1En5qF/g+3AS78j0pQLwgyfiY2Wxdgx1y8O1LC8l/bFlZzV9XkTLM3FGAg)
          apple:
            client-name: apple
            client-id: ENC(NcgbXaGAkFQQQKMatTfBKPslwGNAFPyupnb5CggsLTY=)
        provider:
          naver:
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          apple:
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
      apple:
        team-id: ENC(84yDRtpeK/fwcu9uB2fOh1EhHiYxW9zK)
        key-id: ENC(dwju4g/zLsvwxtTbLTP2VuTri+uoUX3t)
        private-key-path: ENC(Wh2lCpfugr9NofUwUMVqcee4LtdKRrRq+rKTbUiWJY7Ob+yO6rZicJqoEV9Lqa9XQcvTLG4tmD0=)
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
