#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: /app/config/keystore.p12
#    key-store-password: ENC(vvUgNR9gTKm6jTSuHQDLC9QzqN3wH+vU)
#    key-store-type: PKCS12

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

spring:
  jackson:
    time-zone: Asia/Seoul
  application:
    name: stockProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stockdb-mysql.c1m2ggiemzj3.ap-northeast-2.rds.amazonaws.com:3306/stock_schema?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: Fund1121
    time-zone: Asia/Seoul
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
    show-sql: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
      enabled: false

security:
  appKey: PSreY8MuLtMxSoL3SYpAV6hrlYKliaN4tgly
  appSecret: 2tTLlM0d6V+AI2FXuIS6zcR2Ksd4j3uYW1Lb5GgvHxbUc05l9GF7qlHe8S4S0cBpIgM0ZKRK8itJKgFn8aNkqAmnVFYJnVrISYpjWRzkUgFoTVNf4D/ct0YEhR084UQzhOjeqxpU6Tp2GIRJu4Y4ARa4wX087DfZuRU7JKZY4KrNSjlgzXo=

management:
  server:
    port: 9090
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
