jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

spring:
  application:
    name: stockProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(o/t/6E2gqepkhCGzNBKxqTHqdl2am/LXx7oza/aQ+1ORZS9y1NoMWeYad76lBg7AnSmV5bOElouEv3o2S4NSkn6pyrZ0QGOwuskx3CIAQkPCrqYo666ODs7bHzJCu0le4Up7BlE3QRTFBBcKdlnt7KfO0V97XyIxsclC6IXj0cqkzXWLw+2vWACrmhCfdZ6RzTHqYrxRr7I=)
    username: ENC(0YcumuiWmFs1CZfK0RcslQ==)
    password: ENC(41UmOQt2/KKY36ydEZ2QpigL3PJ6oiFq)
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
      enabled: false

security:
  appkey: ENC(FS8DY9wSmCauQ8SGk2CW3avWxPia5c41UDxMHAzzog3AloY5ynPAz1J/vVPvophr)
  appsecret: ENC(cYfISHcPzRSI2OO/N17vf9MD7OOqfp8Zq8+DcsXY+X7PTpbECdwqEDXclOlJfWUwhYZl8yy5bSwvuveEOPpxd5LFg5NtQWIcV63oWdPBzZmaGeJIvu8owdrJd5V07EJWNAHl9z4dZ6nTNTKCgahQ/o6Gy15FHDwFk99hM1TgZzvZ7h1hOsKZt9xbvZvLMtq3UbumkxrCGLbJHSUYK2EhmVXsC6GQmZwSAKJdxAzIvB2PKUDwu3eI5RXcxDyhzRzd)
