server:
  port: 443
  ssl:
    enabled: true
    key-store: /app/config/keystore.p12
    key-store-password: ENC(vvUgNR9gTKm6jTSuHQDLC9QzqN3wH+vU)
    key-store-type: PKCS12

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

spring:
  jackson:
    time-zone: Asia/Seoul
  application:
    name: stockProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(o/t/6E2gqepkhCGzNBKxqTHqdl2am/LXx7oza/aQ+1ORZS9y1NoMWeYad76lBg7AnSmV5bOElouEv3o2S4NSkn6pyrZ0QGOwuskx3CIAQkPCrqYo666ODs7bHzJCu0le4Up7BlE3QRTFBBcKdlnt7KfO0V97XyIxsclC6IXj0cqkzXWLw+2vWACrmhCfdZ6RzTHqYrxRr7I=)
    username: ENC(0YcumuiWmFs1CZfK0RcslQ==)
    password: ENC(41UmOQt2/KKY36ydEZ2QpigL3PJ6oiFq)
    time-zone: Asia/Seoul
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
    show-sql: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
      enabled: false

security:
  appkey: ENC(FS8DY9wSmCauQ8SGk2CW3avWxPia5c41UDxMHAzzog3AloY5ynPAz1J/vVPvophr)
  appsecret: ENC(cYfISHcPzRSI2OO/N17vf9MD7OOqfp8Zq8+DcsXY+X7PTpbECdwqEDXclOlJfWUwhYZl8yy5bSwvuveEOPpxd5LFg5NtQWIcV63oWdPBzZmaGeJIvu8owdrJd5V07EJWNAHl9z4dZ6nTNTKCgahQ/o6Gy15FHDwFk99hM1TgZzvZ7h1hOsKZt9xbvZvLMtq3UbumkxrCGLbJHSUYK2EhmVXsC6GQmZwSAKJdxAzIvB2PKUDwu3eI5RXcxDyhzRzd)

management:
  server:
    port: ENC(YM5iuhoueUzsQ7Cd5Prbug==)
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

endpoints:
  web:
    exposure:
      include: health, info, metrics, prometheus
