app:
  domain:
    prod: ENC(5P9Iq3ZTswvqef+LtMIwKsnvQ0guIfVYyIMmNmYcjDA=)
    test: ENC(uA65wJJ2xUxoDiTPw+99JfevldmMMFdHcK2oJelBhOG1/h0A+HsR96VdRpeaRzl/)
server:
  port: 443
  ssl:
    enabled: true
    key-store: /app/config/keystore.p12
    key-store-password: ENC(vvUgNR9gTKm6jTSuHQDLC9QzqN3wH+vU)
    key-store-type: PKCS12

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

spring:
  jackson:
    time-zone: Asia/Seoul
  application:
    name: stockProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(o/t/6E2gqepkhCGzNBKxqTHqdl2am/LXx7oza/aQ+1ORZS9y1NoMWeYad76lBg7AnSmV5bOElouEv3o2S4NSkn6pyrZ0QGOwuskx3CIAQkPCrqYo666ODs7bHzJCu0le4Up7BlE3QRTFBBcKdlnt7KfO0V97XyIxsclC6IXj0cqkzXWLw+2vWACrmhCfdZ6RzTHqYrxRr7I=)
    username: ENC(0YcumuiWmFs1CZfK0RcslQ==)
    password: ENC(41UmOQt2/KKY36ydEZ2QpigL3PJ6oiFq)
    time-zone: Asia/Seoul
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
    show-sql: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
      enabled: false
  jwt:
    secret: ENC(ZtLQKC+5jIxK8fYB7W6XZ3mkCr3ueVGBVYTa1SfpAsnsSKUw2k5lHD+egat0VF0fyQH9apHpl5o=)
    access-expiration-ms: ENC(LC2BPxRUYKGUHFikipEopQ==)
    refresh-expiration-ms: ENC(vIwhX3e0QNiMf9DT3qx6tviWchTH1OL7)
  security:
    appkey: ENC(x03pW1tjWZPkly9PCQWLKQd94SpUnXcUGJ2y7NcdcAM5/knSG6/mnt1eEiHqIgIx)
    appsecret: ENC(lY5EPC0PWewfMk5owO0kTYSWAL5HSIW5pHXjWNl3fZggYrDWTjOHEy2zfkaO7lfIMg6OCzYkvKS9abf1ERQtcatpX/4dc1LEsCmgImvmIghj6m5r7SlBcBsSraMr70vs39wFo/9AVwiyHY0idIbrfNJwW9ZWSJM2NKDhuSo0K3hI1kDWjcVkRTRkdtjlMk4YxMqGgJ5lcx3EVmHqp7+RSYTx+j64lLUrSjt56wXQqgBI95wwzAmTq6UVJRhPyNwJ)
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ENC(iujxejF3nI3d/FDLv35lDVvqkRJjyhJ360wQIz58XVI=)
            client-secret: ENC(UTJocZk/Qdn55DvJDhT6EqoUvrBHn8a7)
            redirect-uri: ENC(ENKzIy0M0ZmX+xSYduyLKNjV6zcevb68xuJpnzd8FW2nup0EHiOwDGi3TKvVVXI+H73v+ubkY+m5v1V6iPfx4g==)
            authorization-grant-type: authorization_code
            scope:
              - email
          kakao:
            client-name: kakao
            client-id: ENC(Z/azUck8uPg4sccZR9YrtHd2rhbnlhqb3oItGrWwV8hA1ccWVRlQipEDVzK6i9y5)
            client-secret: ENC(61bQlbYM8ifrJHOUKFkAvmbhq2O5MzMB/wGPZBW9GwL4psRNxGSXB9vGCUefASah)
            redirect-uri: ENC(qKNpIr7n0QCtmhiNPjKC+jI8oP5w5LWvGnO8xcHrYdeESoUtes77OsdiCYcmNutUcNP3heNE5dSeZtvHPQ34pg==)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
          google:
            client-name: google
            client-id: ENC(7umyS0XfZFCY4EBA9S0jsf95iyn2hN11TVDm9mQKRwfGCOpCd6GMRAAmPH+QTs0hI1t4Z562K4nHnTDwhkyWeALGEXRWgaXkIAo43mD44OFkOOKQMtSOkw==)
            client-secret: ENC(Dxg7FyFQHCHZijZyU98AokMA8bWiDBxP7vwABBtPs8VGAOvxI2E4sVVyW9tiVhUo)
            redirect-uri: ENC(5FGmPL3woEys/pHeIt9C2W4DNC3K6YZaTHHiC11Nllkva6k01yfDby4sV2YRCcTzahdHFpPwKHihogxT7K+uLQ==)
            authorization-grant-type: authorization_code
            scope:
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true